<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PepeWapOSx10.Dominio\PepeWapOSx10.Dominio.csproj" />
    <ProjectReference Include="..\PepeWapOSx10.Datos\PepeWapOSx10.Datos.csproj" />
    <ProjectReference Include="..\PepeWapOSx10.Calendario\PepeWapOSx10.Calendario.csproj" />
    <ProjectReference Include="..\PepeWapOSx10.Shell.Widgets\PepeWapOSx10.Shell.Widgets.csproj" />
    <ProjectReference Include="..\PepeWapOSx10.Shell.Iconos\PepeWapOSx10.Shell.Iconos.csproj" />
    <ProjectReference Include="..\PepeWapOSx10.Shell.Taskbar\PepeWapOSx10.Shell.Taskbar.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
